export default {
  auth: "/auth" as const,
  login: "/auth/login" as const,
  forgotPassword: "/auth/forgot-password" as const,
  forgotPasswordMailSent: "/auth/forgot-password-mail-sent" as const,
  resetPassword: "/auth/reset-password" as const,
  register: "/auth/register" as const,
  onboarding: "/onboarding" as const,
  welcome: "/onboarding/welcome" as const,
  getStarted: "/onboarding/get-started" as const,
  emailSent: "/onboarding/email-sent" as const,
  emailVerified: "/onboarding/email-verified" as const,
  home: "/" as const,
  budget: "/budget" as const,
  createBudget: "/budget/create" as const,
  budgets: (key: string) => `/budget/${key}`,
};
